### ISSUE TITLE
htcondor_dags-0.1.1 request

### ISSUE THREAD

**Issue by duncanmmacleod** [htcondor/htcondor-dags#5]
It would be great to get `htcondor_dags-0.1.1` uploaded to PyPI, mainly to have a release that includes the fix from #3. Thanks.

**Comment by JoshKarpel** [comment]
Released, and I checked that the source install works for me. Could you check that it works for you?

**Comment by duncanmmacleod** [comment]
Thanks @JoshKarpel, I can now successfully build RPMs from that tarball.
